export const projects = [
  {
    id: 1,
    title: 'React Native Expo Weather App',
    description: 'A weather app using Expo and OpenWeather API.',
    details: 'Weather app built with React Native and Expo, utilizing the OpenWeather API to fetch real-time weather data.',
    link: 'https://github.com/themrsami/react-native-expo-weather-app-openweather_api',
    tech: ['React Native', 'JavaScript'],
  },
  {
    id: 2,
    title: 'Learning Management System',
    description: 'A React Native based LMS.',
    details: 'Learning Management System built with React Native, providing functionalities for managing courses, students, and instructors.',
    link: 'https://github.com/themrsami/LMS-Learning-Management-System-React-Native',
    tech: ['React Native', 'JavaScript'],
  },
  {
    id: 3,
    title: 'React Native Weather App',
    description: 'A basic weather app built with React Native.',
    details: 'Weather app using React Native, fetching weather data to display current conditions and forecasts.',
    link: 'https://github.com/themrsami/React-Native-Whether-App',
    tech: ['React Native', 'JavaScript'],
  },
  {
    id: 4,
    title: 'GoFile to Google Drive Downloader',
    description: 'Download files from GoFile to Google Drive using Google Colab.',
    details: 'Script to remotely download files from GoFile and save them to Google Drive via Google Colab.',
    link: 'https://github.com/themrsami/GoFile-To-GoogleDrive-Downloader-Remotely-for-Google-Collab',
    tech: ['Python', 'Jupyter Notebook'],
  },
  {
    id: 5,
    title: 'Google Drive Uploader',
    description: 'Script for uploading files to Google Drive from Google Colab.',
    details: 'Enables parallel downloading and uploading of files from Google Drive using Python and concurrent futures.',
    link: 'https://github.com/themrsami/Google-Collab-Script-to-Remotely-Upload-Files-to-Your-Google-Drive',
    tech: ['Python', 'Jupyter Notebook'],
  },
  {
    id: 6,
    title: 'Sanfoundry MCQ Scraper',
    description: 'Web scraper for extracting MCQs from Sanfoundry.',
    details: 'Scraper built with Python and HTML to collect multiple choice questions from Sanfoundry for offline use.',
    link: 'https://github.com/themrsami/Sanfoundry-MCQs-Scraper',
    tech: ['Python', 'HTML'],
  },
  {
    id: 7,
    title: 'Monkeytype Autotyper',
    description: 'Autotyper for Monkeytype with a graphical user interface.',
    details: 'Python application with a GUI to automate typing on Monkeytype, built using PyQt5.',
    link: 'https://github.com/themrsami/Monkeytype-Autotyper-with-GUI',
    tech: ['Python'],
  },
  {
    id: 8,
    title: 'PDF Hyperlink Extractor',
    description: 'Tool to extract hyperlinks from PDF files.',
    details: 'A PyQt5 and PyMuPDF based tool for extracting and categorizing links from PDFs.',
    link: 'https://github.com/themrsami/ExtractHyperlinksFromPDF',
    tech: ['Python'],
  },
  {
    id: 9,
    title: 'MovieLand',
    description: 'Movie site built with React.js using OMDBAPI.',
    details: 'Dynamic movie site leveraging OMDBAPI for movie data, with robust search functionality.',
    link: 'https://github.com/themrsami/MovieLand_With_OMDBAPI_React.js',
    tech: ['React', 'JavaScript'],
  },
  {
    id: 10,
    title: 'Personal Website',
    description: 'Personal website built with React.js and Next.js.',
    details: 'A personal website showcasing my projects, skills, and experience.',
    link: 'https://github.com/themrsami/themrsami.github.io',
    tech: ['React', 'Next.js', 'JavaScript'],
  },
  {
    id: 11,
    title: 'Magic UI',
    description: 'A React.js component library for building user interfaces.',
    details: 'A collection of reusable React components for building fast and efficient user interfaces.',
    link: 'https://github.com/themrsami/Magic-UI',
    tech: ['React', 'JavaScript'],
  },
  {
    id: 12,
    title: 'Movie App',
    description: 'A movie app built with React Native.',
    details: 'A mobile app for browsing and searching movies, built with React Native and Expo.',
    link: 'https://github.com/themrsami/react-native-movie-app',
    tech: ['React Native', 'JavaScript'],
  },
];